INSERT INTO avis (contenu, note) VALUES
('Excellent service, très professionnel et rapide !', 5),
('Une expérience parfaite, je recommande vivement.', 5),
('Très satisfait, travail de qualité et personnel agréable.', 5),
('Bon service et personnel gentil.', 4),
('Très satisfait.', 5),
('Service parfait, je recommande.', 5),
('Travail bien fait, très méticuleux.', 5),
('Très bon accueil et prestation de grande qualité.', 5),
('Parfait du début à la fin, je referai appel à eux!', 5),
('Service impeccable, technicien très compétent.', 5),
('Rien à redire, tout était excellent.', 5),
('Prestation rapide et efficace, merci!', 5),
('Très pro, résultat au-delà de mes attentes.', 5),
('Service correct mais un peu lent.', 4),
('Satisfait dans l\'ensemble.', 4),
('Très bonne communication et travail soigné.', 5),
('Je suis ravi du résultat final.', 5),
('Personnel sympathique et compétent.', 5),
('Prix raisonnable pour la qualité offerte.', 5),
('Petit problème mais rapidement résolu.', 4),
('Excellente réactivité, merci!', 5),
('Travail nickel, je suis impressionné.', 5),
('Service au top comme d\'habitude.', 5),
('Un peu déçu par certains détails.', 3),
('Je n\'hésiterai pas à refaire appel à eux.', 5),
('Tout simplement parfait!', 5);