INSERT INTO comptes (id, nom, email, mot_de_passe, client_id) VALUES
(1, 'Hicham Serifi-Ayemamouni', 'serifihicham@hotmail.fr', 'password1', NULL),
(2, 'Emma Vermeulen', 'emma.vermeulen@hotmail.com', 'password2', NULL),
(3, 'Noah Janssens', 'noah.janssens@yahoo.be', 'password3', NULL),
(4, 'Liam Peeters', 'liam.peeters@skynet.be', 'password4', NULL),
(5, 'Elise Maes', 'elise.maes@proximus.be', 'password5', NULL),
(6, 'Louis Van den Broeck', 'louis.vdb@telenet.be', 'password6', NULL),
(7, 'Sophie Goossens', 'sophie.goossens@voo.be', 'password7', NULL),
(8, 'Nathan Dubois', 'nathan.dubois@gmail.com', 'password8', NULL),
(9, 'Charlotte Lemaire', 'charlotte.lemaire@yahoo.fr', 'password9', NULL),
(10, 'Thomas De Smet', 'thomas.desmet@outlook.com', 'password10', NULL),
(11, 'Julie Claes', 'julie.claes@hotmail.be', 'password11', NULL),
(12, 'Mathis Devos', 'mathis.devos@gmail.com', 'password12', NULL),
(13, 'Hugo Van Damme', 'hugo.vandamme@telenet.be', 'password13', NULL),
(14, 'Laura Wouters', 'laura.wouters@skynet.be', 'password14', NULL),
(15, 'Bastien Simon', 'bastien.simon@voo.be', 'password15', NULL),
(16, 'Manon Lefebvre', 'manon.lefebvre@gmail.com', 'password16', NULL),
(17, 'François Garnier', 'francois.garnier@example.com', 'password17', NULL),
(18, 'Océane Lemoine', 'oceane.lemoine@testmail.com', 'password18', NULL),
(99, 'Thierry Dupuis', 'thierry.dupuis@demo.net', 'password99', NULL),
(100, 'Nathalie Lefevre', 'nathalie.lefevre@example.com', 'password100', NULL);
