INSERT INTO services (service, description, prix) VALUES
('Plomberie Générale', 'Installation et réparation de plomberie', 150.00),
('Chauffage', 'Installation et maintenance des systèmes de chauffage', 250.00),
('Débouchage', 'Débouchage des canalisations et WC', 100.00),
('Rénovation salle de bain', 'Remplacement complet des équipements sanitaires', 500.00),
('Dépannage Urgent', 'Intervention rapide sur fuites et pannes', 200.00),
('Installation panneaux photovoltaïques', 'Pose et raccordement de panneaux solaires', 1200.00),
('Entretien panneaux photovoltaïques', 'Nettoyage et vérification du bon fonctionnement', 300.00),
('Diagnostic photovoltaïque', 'Analyse des performances et détection de pannes', 150.00),
('Remplacement onduleur solaire', 'Changement et configuration de l’onduleur', 800.00),
('Installation chaudière gaz', 'Pose et raccordement d\'une chaudière à gaz', 1500.00),
('Réparation fuite gaz', 'Réparation de fuites sur les conduites de gaz', 250.00),
('Rénovation plomberie cuisine', 'Mise à jour des installations de plomberie dans la cuisine', 400.00),
('Installation adoucisseur d\'eau', 'Pose d\'un adoucisseur pour réduire la dureté de l\'eau', 600.00),
('Installation climatisation', 'Pose et mise en service de systèmes de climatisation', 1800.00),
('Entretien chaudière', 'Vérification et nettoyage de chaudières à gaz ou au fioul', 150.00),
('Installation robinetterie', 'Pose de robinets pour cuisine et salle de bain', 75.00),
('Installation chauffe-eau', 'Installation d\'un chauffe-eau électrique ou à gaz', 800.00),
('Installation de ballon d\'eau chaude', 'Pose et raccordement d\'un ballon d\'eau chaude', 900.00),
('Remplacement de tuyaux', 'Remplacement de tuyaux pour chauffage ou eau', 300.00),
('Réparation tuyaux', 'Réparation de fuites ou de cassures dans les tuyaux', 150.00),
('Entretien climatisation', 'Vérification et entretien de systèmes de climatisation', 250.00),
('Installation douche', 'Pose de douches avec carrelage et plomberie', 1000.00),
('Pose carrelage salle de bain', 'Installation de carrelage dans les salles de bain', 600.00),
('Installation WC suspendu', 'Pose de WC suspendu avec raccordement', 700.00),
('Chauffage au sol', 'Installation de chauffage au sol dans les pièces de vie', 1200.00),
('Rénovation chauffage', 'Rénovation complète du système de chauffage', 1800.00),
('Réparation de chauffe-eau', 'Réparation d\'un chauffe-eau défectueux', 250.00),
('Maintenance de chaudières', 'Vérification et entretien des chaudières', 200.00),
('Installation de radiateurs', 'Pose de nouveaux radiateurs dans votre logement', 400.00),
('Entretien chauffage central', 'Entretien des systèmes de chauffage central', 250.00),
('Dépannage plombier', 'Intervention d\'urgence pour fuites et pannes', 200.00),
('Installation de lavabo', 'Pose de lavabos dans les salles de bain', 150.00),
('Installation robinet cuisine', 'Installation de robinet dans la cuisine', 100.00),
('Débouchage canalisations', 'Débouchage des canalisations d\'eaux usées', 120.00),
('Réparation radiateur', 'Réparation de radiateurs endommagés ou obstrués', 250.00),
('Installation de chauffe-eau thermodynamique', 'Installation d\'un chauffe-eau thermodynamique', 1800.00),
('Pose adoucisseur d\'eau', 'Installation d\'un adoucisseur pour traitement de l\'eau', 600.00),
('Rénovation complète de salle de bain', 'Rénovation de la salle de bain complète avec plomberie et décoration', 3000.00),
('Pose de baignoire', 'Installation d\'une nouvelle baignoire dans la salle de bain', 700.00),
('Installation de cumulus', 'Installation et entretien de cumulus dans les habitations', 500.00),
('Chauffage piscine', 'Installation de chauffage pour piscine extérieure', 1500.00),
('Entretien de plomberie', 'Entretien annuel des systèmes de plomberie', 250.00),
('Rénovation installation gaz', 'Remplacement et mise à jour des installations de gaz', 1800.00),
('Installation de chauffe-eau à gaz', 'Pose et installation de chauffe-eau à gaz', 1000.00),
('Dépannage fuite eau', 'Intervention pour fuite d\'eau à tout moment', 150.00),
('Installation de VMC', 'Pose de ventilation mécanique contrôlée pour la salle de bain', 600.00),
('Pose d\'un chauffe-eau solaire', 'Installation d\'un chauffe-eau solaire écologique', 1800.00),
('Réparation fuite de gaz', 'Réparation d\'une fuite de gaz dans votre installation', 300.00),
('Réparation de tuyauterie PVC', 'Réparation des tuyaux PVC dans les canalisations', 150.00),
('Réparation fuite sous évier', 'Réparation de fuite d\'eau sous un évier', 100.00),
('Installation de chauffe-eau solaire', 'Installation de chauffe-eau solaire pour eau chaude sanitaire', 1500.00),
('Installation de robinet thermostatique', 'Pose de robinet thermostatique pour régulation de température', 200.00),
('Entretien chaudières à condensation', 'Vérification et entretien des chaudières à condensation', 250.00),
('Installation d\'adoucisseur', 'Installation d\'un adoucisseur d\'eau', 800.00),
('Réparation fuite WC', 'Réparation des fuites dans les WC', 100.00),
('Remplacement de pompe à chaleur', 'Installation et remplacement des pompes à chaleur', 3000.00),
('Dépannage plomberie', 'Intervention de dépannage sur tous types de plomberie', 200.00),
('Installation de radiateurs à eau', 'Pose de radiateurs à eau pour système de chauffage central', 800.00),
('Entretien plomberie chauffage', 'Entretien et révision des tuyaux de chauffage et de plomberie', 250.00),
('Pose de tuyaux cuivre', 'Installation de tuyaux en cuivre pour plomberie', 300.00),
('Installation de cabine de douche', 'Pose et raccordement de cabine de douche', 700.00),
('Réparation tuyau gaz', 'Réparation des fuites de gaz dans les tuyaux', 250.00),
('Installation WC', 'Pose de WC dans une salle de bain ou salle d\'eau', 500.00),
('Réparation chaudière', 'Réparation de chaudières de tout type', 350.00),
('Installation de dispositifs anti-calcaire', 'Installation d\'appareils anti-calcaire', 200.00),
('Installation chauffe-eau à panneaux solaires', 'Pose d\'un chauffe-eau avec panneaux solaires', 2200.00),
('Rénovation plomberie ancienne maison', 'Mise à jour de la plomberie dans une maison ancienne', 1500.00),
('Installation de dispositifs d\'économies d\'eau', 'Pose de dispositifs pour économiser l\'eau', 400.00),
('Rénovation de salle de bain moderne', 'Création d\'une salle de bain moderne et fonctionnelle', 3500.00),
('Installation de chauffe-eau électrique', 'Installation d\'un chauffe-eau électrique', 800.00),
('Installation de chauffe-eau instantané', 'Pose de chauffe-eau instantané pour eau chaude', 1000.00),
('Dépannage fuite d\'eau extérieure', 'Réparation des fuites d\'eau à l\'extérieur de la maison', 150.00),
('Installation robinet bain', 'Pose de robinet de bain avec raccordement', 250.00),
('Rénovation sanitaire', 'Rénovation des équipements sanitaires dans une salle de bain', 1200.00),
('Installation chauffe-eau en série', 'Installation de plusieurs chauffe-eaux en série', 5000.00),
('Réparation de tuyaux anciens', 'Réparation de tuyaux anciens dans les murs', 350.00),
('Entretien réservoir de chasse', 'Vérification et entretien du réservoir de chasse des WC', 100.00),
('Installation de douche à l\'italienne', 'Pose d\'une douche à l\'italienne', 1200.00),
('Réparation plomberie extérieure', 'Réparation de plomberie à l\'extérieur du bâtiment', 200.00),
('Installation de thermostats connectés', 'Installation et configuration de thermostats intelligents', 300.00),
('Réparation fuite d\'eau sous lavabo', 'Réparation de fuites d\'eau sous un lavabo de cuisine ou salle de bain', 100.00),
('Rénovation plomberie salle de bain', 'Mise à jour de la plomberie dans une salle de bain complète', 1500.00),
('Pose de robinet thermostatique', 'Installation de robinet thermostatique pour réguler la température', 150.00),
('Installation de fontaine à eau', 'Pose d\'une fontaine d\'eau dans le jardin ou intérieur', 350.00),
('Entretien du système de chauffage au gaz', 'Vérification et entretien des chauffages au gaz', 250.00),
('Installation de chauffe-eau à pompe à chaleur', 'Installation de chauffe-eau thermodynamique avec pompe à chaleur', 2000.00),
('Installation d\'une chaudière à condensation', 'Pose d\'une chaudière à condensation à haut rendement énergétique', 2500.00),
('Réparation de radiateur électrique', 'Réparation de radiateurs électriques défectueux', 150.00),
('Rénovation de plomberie dans un appartement', 'Révision complète de la plomberie dans un appartement', 1200.00),
('Installation de système de filtration d\'eau', 'Pose d\'un système de filtration d\'eau pour toute la maison', 500.00),
('Chauffage à air pulsé', 'Installation d\'un système de chauffage à air pulsé dans la maison', 2200.00),
('Réparation de chauffe-eau instantané', 'Réparation de chauffe-eau instantané défectueux', 350.00),
('Installation de chaudière fioul', 'Pose de chaudière à fioul pour chauffage et eau chaude', 1800.00),
('Pose d\'un adoucisseur d\'eau pour piscine', 'Installation d\'un adoucisseur d\'eau pour le système de piscine', 1200.00),
('Dépannage chauffe-eau à gaz', 'Intervention rapide pour réparer un chauffe-eau à gaz', 250.00),
('Installation de régulateur de pression', 'Pose de régulateur de pression pour réseau d\'eau', 350.00),
('Installation de cuve de récupération d\'eau de pluie', 'Pose de cuve pour récupérer l\'eau de pluie pour arrosage ou autres', 1000.00),
('Réparation chauffe-eau solaire', 'Réparation d\'un chauffe-eau solaire défectueux', 300.00),
('Installation de chauffage à infrarouge', 'Pose de chauffage à infrarouge pour pièces spécifiques', 1500.00),
('Réparation système de climatisation', 'Réparation des unités de climatisation défectueuses', 250.00),
('Entretien annuel chaudière à gaz', 'Entretien complet annuel des chaudières à gaz', 200.00),
('Installation d\'un chauffe-eau à accumulation', 'Pose d\'un chauffe-eau à accumulation pour grande consommation d\'eau', 1200.00),
('Pose de tuyauterie en PER', 'Installation de tuyauterie en PER pour distribution d\'eau et chauffage', 800.00),
('Installation de désembouage chauffage', 'Installation d\'un système de désembouage pour radiateurs', 500.00),
('Réparation chauffe-eau à pompe à chaleur', 'Réparation d\'un chauffe-eau thermodynamique', 400.00),
('Entretien complet des canalisations', 'Inspection et entretien de toutes les canalisations d\'eau', 150.00),
('Entretien plomberie système chauffage', 'Vérification et entretien des systèmes de chauffage', 250.00);

