INSERT INTO demande_devis (client_id, nom, email, telephone, message, statut) VALUES
(NULL, 'Jean Dupont',      'jean.dupont@example.com',      '0471000001', 'Réparation fuite lavabo',                    'EN_ATTENTE'),
(NULL, 'Bob Sule',         'bob.sule@example.com',         '0471000002', 'Installation douche italienne',              'TRAITE'),
(NULL, 'Ahmed Benali',     'ahmed.benali@example.com',     '0471000003', 'Remplacement chauffe-eau',                   'EN_ATTENTE'),
(NULL, 'Sophie Martin',    'sophie.martin@example.com',    '0471000004', 'Désembouage radiateurs',                     'TRAITE'),
(NULL, 'David Moreau',     'david.moreau@example.com',     '0471000005', 'Pose de mitigeur thermostatique',            'EN_ATTENTE'),
(NULL, 'Laura Petit',      'laura.petit@example.com',      '0471000006', 'Réparation chasse d’eau WC',                 'TRAITE'),
(NULL, 'Karim Ouali',      'karim.ouali@example.com',      '0471000007', 'Installation évier cuisine',                 'EN_ATTENTE'),
(NULL, 'Isabelle Leroy',   'isabelle.leroy@example.com',   '0471000008', 'Remplacement siphon salle de bain',          'EN_ATTENTE'),
(NULL, 'Thomas Bernard',   'thomas.bernard@example.com',   '0471000009', 'Pose cabine de douche',                      'TRAITE'),
(NULL, 'Nadia Saidi',      'nadia.saidi@example.com',      '0471000010', 'Réparation ballon d’eau chaude',             'EN_ATTENTE'),
(NULL, 'Yassine El Fassi', 'yassine.elfassi@example.com',  '0471000011', 'Débouchage canalisation principale',         'TRAITE'),
(NULL, 'Maya Robert',      'maya.robert@example.com',      '0471000012', 'Installation robinet extérieur',             'EN_ATTENTE'),
(NULL, 'Rachid Tazi',      'rachid.tazi@example.com',      '0471000013', 'Remplacement colonne de douche',             'TRAITE'),
(NULL, 'Hélène Caron',     'helene.caron@example.com',     '0471000014', 'Réparation fuite tuyauterie cuivre',         'EN_ATTENTE'),
(NULL, 'Paul Lambert',     'paul.lambert@example.com',     '0471000015', 'Installation chauffe-eau instantané',        'TRAITE'),
(NULL, 'Inès Maillard',    'ines.maillard@example.com',    '0471000016', 'Remplacement joints robinet',                'EN_ATTENTE'),
(NULL, 'Omar Bensaid',     'omar.bensaid@example.com',     '0471000017', 'Pose WC suspendu',                           'TRAITE'),
(NULL, 'Clara Denis',      'clara.denis@example.com',      '0471000018', 'Réparation robinet mélangeur',               'EN_ATTENTE'),
(NULL, 'Samir Zahidi',     'samir.zahidi@example.com',     '0471000019', 'Détection fuite invisible',                  'EN_ATTENTE'),
(NULL, 'Léa Marchand',     'lea.marchand@example.com',     '0471000020', 'Rénovation complète salle de bain',          'TRAITE');